export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD'

export const INCREMENT_ASYNC = 'INCREMENT_ASYNC'
export const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC'

export const COUNTDOWN_TERMINATED = 'COUNTDOWN_TERMINATED'
export const COUNTDOWN_FINISH = 'COUNTDOWN_FINISH'

export const MOVIE_FETCHING = 'MOVIE_FETCHING'
export const MOVIE_FETCH = 'MOVIE_FETCH'
export const MOVIE_FETCH_SUCCESS = 'MOVIE_FETCH_SUCCESS'

export const MOVIE_DETAIL_FETCHING = 'MOVIE_DETAIL_FETCHING'
export const MOVIE_DETAIL_FETCH = 'MOVIE_DETAIL_FETCH'
export const MOVIE_DETAIL_FETCH_SUCCESS = 'MOVIE_DETAIL_FETCH_SUCCESS'

export const MOVIE_SEARCHING = 'MOVIE_SEARCHING'
export const MOVIE_SEARCHING_START = 'MOVIE_SEARCHING_START'
export const MOVIE_SEARCHING_SUCCESS = 'MOVIE_SEARCHING_SUCCESS'

export const REGISTER_SAVE_EMAIL = 'REGISTER_SAVE_EMAIL'

export const LOGIN_SAVE_DATA = 'LOGIN_SAVE_DATA'

export const ACCOUNT_SAVE_DATA = 'ACCOUNT_SAVE_DATA'

